package blue.endless.module2_2;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.EOFException;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.Arrays;
import java.util.Random;

/**
 * Represents five random integers and five random doubles. Because the file format does not include length information,
 * any array length besides five would create undefined behavior and is not allowed. Data integrity is enforced via
 * static factory methods. Additionally, this class is immutable.
 */
public class RandomNumberEntry {
	private int[] ints = new int[5];
	private double[] doubles = new double[5];
	
	/**
	 * This class cannot be constructed without using its static factory methods.
	 * @see #fromInput(DataInput)
	 * @see #fromRandom(Random)
	 */
	private RandomNumberEntry() {}
	
	/**
	 * Gets the five integer values stored in this entry. The returned array is a copy.
	 * @return The integer values stored in this entry
	 */
	public int[] ints() { return Arrays.copyOf(ints, ints.length); }
	
	/**
	 * Gets a String representation of the integer values stored in this entry.
	 * @return A String describing the integer values in this entry
	 */
	public String describeInts() {
		return Arrays.toString(ints);
	}
	
	/**
	 * Gets the five double values stored in this entry. The returned array is a copy.
	 * @return The double values stored in this entry
	 */
	public double[] doubles() { return Arrays.copyOf(doubles, doubles.length); }
	
	/**
	 * Gets a String representation of the Double values stored in this entry.
	 * This method is purely for display and debug purposes, and only shows one decimal place of precision.
	 * @return A String describing the double values in this entry
	 */
	public String describeDoubles() {
		NumberFormat format = NumberFormat.getNumberInstance();
		format.setMinimumFractionDigits(1);
		format.setMaximumFractionDigits(1);
		
		StringBuilder result = new StringBuilder("[");
		for(int i=0; i<doubles.length; i++) {
			result.append(format.format(doubles[i]));
			if (i<doubles.length-1) result.append(", ");
		}
		result.append("]");
		
		return result.toString();
	}
	
	/**
	 * Writes this RandomNumberEntry out to the specified binary output
	 * @param out The output to write this entry to
	 * @throws IOException if there was a problem writing the data
	 */
	public void write(DataOutput out) throws IOException {
		for(int i=0; i<ints.length; i++) {
			out.writeInt(ints[i]);
		}
		for(int i=0; i<doubles.length; i++) {
			out.writeDouble(doubles[i]);
		}
	}
	
	/**
	 * Creates a RandomNumberEntry using random numbers generated by the specified Random instance.
	 * @param random The PRNG to use to generate random values for the object's tables
	 * @return A new RandomNumberEntry filled with fresh random numbers
	 */
	public static RandomNumberEntry fromRandom(Random random) {
		RandomNumberEntry entry = new RandomNumberEntry();
		for(int i=0; i<entry.ints.length; i++) {
			entry.ints[i] = random.nextInt(100);
		}
		for(int i=0; i<entry.doubles.length; i++) {
			entry.doubles[i] = random.nextDouble(10.0);
		}
		
		return entry;
	}
	
	/**
	 * Reads one entry of five ints and five doubles from the data stream
	 * @param in The data stream to read from
	 * @return A RandomNumberEntry representing the data read from the stream
	 * @throws EOFException If the end of the file was reached before a complete entry could be constructed
	 * @throws IOException  If an error occurred reading the data
	 */
	public static RandomNumberEntry fromInput(DataInput in) throws EOFException, IOException {
		RandomNumberEntry entry = new RandomNumberEntry();
		for(int i=0; i<entry.ints.length; i++) {
			entry.ints[i] = in.readInt();
		}
		for(int i=0; i<entry.doubles.length; i++) {
			entry.doubles[i] = in.readDouble();
		}
		
		return entry;
	}
}