plugins {
	id 'application';
}

application {
	mainClass = "blue.endless.module11_2.App";
	executableDir = ".";
}

repositories {
	mavenCentral();
}

dependencies {
	implementation "blue.endless:jankson:1.2.3";
}

java {
	sourceCompatibility = "1.17";
	targetCompatibility = "1.17";
}

compileJava.options.encoding='UTF-8'

sourceSets {
	main {
		java {
			srcDirs = ['src'];
		}
	}
}
